### ISSUE TITLE
On Python 3 rodeo doesn't run

### ISSUE THREAD

**Issue by davaco** [yhat/rodeo#16]
It seems Rodeo does not support Python 3? I get this stack trace, using anaconda for Python3. For Python2 it works fine.

Traceback (most recent call last):
  File "/Users/dcoevord/anaconda3/bin/rodeo", line 9, in <module>
    load_entry_point('rodeo==0.2.0', 'console_scripts', 'rodeo')()
  File "/Users/dcoevord/anaconda3/lib/python3.4/site-packages/setuptools-15.1-py3.4.egg/pkg_resources/__init__.py", line 546, in load_entry_point
  File "/Users/dcoevord/anaconda3/lib/python3.4/site-packages/setuptools-15.1-py3.4.egg/pkg_resources/__init__.py", line 2666, in load_entry_point
  File "/Users/dcoevord/anaconda3/lib/python3.4/site-packages/setuptools-15.1-py3.4.egg/pkg_resources/__init__.py", line 2339, in load
  File "/Users/dcoevord/anaconda3/lib/python3.4/site-packages/setuptools-15.1-py3.4.egg/pkg_resources/__init__.py", line 2345, in resolve
  File "/Users/dcoevord/anaconda3/lib/python3.4/site-packages/rodeo/cli.py", line 26, in <module>
    from rodeo import main
ImportError: cannot import name 'main'

**Comment by ericchiang** [comment]
Not an expert in python3. Any idea what we're doing wrong with the imports?

The file structure seems really straight forward

```
rodeo/
  __init__.py
  cli.py
  rodeo.py
```

`cli.py` is just calling `from rodeo import main` where `main` is a function defined in `rodeo.py`

**Comment by glamp** [comment]
it needs to be relative. i think it's

```
from .rodeo import main
```

**Comment by glamp** [comment]
d3e426f4a2a79ec934f763de551d89e6b7fb9fdc

**Comment by glamp** [comment]
fixed in 0.2.1 https://pypi.python.org/pypi/rodeo/0.2.1

**Comment by microamp** [comment]
Still failing with v0.2.3. 

```
~ $ sudo pip install rodeo
```
```
Collecting rodeo
  Using cached rodeo-0.2.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): ipython>=3.0.0 in /usr/lib/python3.4/site-packages (from rodeo)
Requirement already satisfied (use --upgrade to upgrade): Flask>=0.10.1 in /usr/lib/python3.4/site-packages (from rodeo)
Requirement already satisfied (use --upgrade to upgrade): jedi in /usr/lib/python3.4/site-packages (from rodeo)
Requirement already satisfied (use --upgrade to upgrade): docopt in /usr/lib/python3.4/site-packages (from rodeo)
Requirement already satisfied (use --upgrade to upgrade): pyzmq>=13 in /usr/lib/python3.4/site-packages (from rodeo)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/lib/python3.4/site-packages (from Flask>=0.10.1->rodeo)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/lib/python3.4/site-packages (from Flask>=0.10.1->rodeo)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/lib/python3.4/site-packages (from Flask>=0.10.1->rodeo)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/lib/python3.4/site-packages (from Jinja2>=2.4->Flask>=0.10.1->rodeo)
Installing collected packages: rodeo
  Running setup.py install for rodeo
Successfully installed rodeo-0.2.3
```
```
~ $ rodeo
```
```
Traceback (most recent call last):
  File "/usr/bin/rodeo", line 9, in <module>
    load_entry_point('rodeo==0.2.3', 'console_scripts', 'rodeo')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 546, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2666, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2339, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2345, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/rodeo/cli.py", line 30, in <module>
    from rodeo import main
ImportError: cannot import name 'main'
```

The version of Python tested against
```
~ $ python --version
```
```
Python 3.4.3
```
