### ISSUE TITLE
Rodeo hangs after being idle and then executing a command

### ISSUE THREAD

**Issue by ben519** [yhat/rodeo#323]
Version: 1.4.8
OSX 10.11.5

How to reproduce this bug:
1) Open Rodeo
2) In a fresh new script (or an existing one) put any valid python command, e.g. `1+1`.  Execute it.
3) Let Rodeo be idle for about 60 (maybe 120?) seconds.
4) Try to execute the same command again.  When I do this, the Rodeo console freezes.

**Comment by glamp** [comment]
Very interesting. I was able to reproduce. What's really interesting is that if your 2nd command sets a variable (i.e. `x = 1`), `x` shows up in the Environment tab.

**Comment by TakenPilot** [comment]
It's not that anything crashes.  The graphical console is just losing the prompt, and is being left in the "output" state.  It thinks it's waiting for output.  I'm able to reproduce this by reseting the console with a `cmd+R`.  

We just need to handle the "reset" command the prompt better.

**Comment by TakenPilot** [comment]
Fixed with latest merge, building the new version now.

**Comment by richardagalvez** [comment]
As of version 2.5.2, I am still experiencing this problem. This is the Mac OS X version 10.12.5
