### ISSUE TITLE
Not seeing any output values

### ISSUE THREAD

**Issue by milesizzo** [yhat/rodeo#71]
I've pulled the latest code and deployed, and I'm not getting any output in the interpreter view. Here is an example output:

```
Welcome to IPython!
>>> 

>>> print "hello"

>>> x = 5

>>> x

>>> print "blah"

>>> x

>>> ?print
>>> 
```

I'm assuming I should at least see the value of `5` (if not the output of `print`). I also didn't get any help on the `print` command when executing that last item.

Also, I'm assuming that executing code with "cmd+enter" is "ctrl+enter" under Windows?

**Comment by eduvik** [comment]
I'm getting the same issue - running Windows 8.1

**Comment by superfuji57** [comment]
Same issue on OSX for me.

**Comment by eduvik** [comment]
I've just tried it with python 2.7 and it works; the problem only appeared for me running it on python 3.4.

**Comment by milesizzo** [comment]
I've pulled the latest sources and this still happens. FWIW I'm using Python 2.7.6, Ubuntu Trusty (64-bit), and Chrome 42.0.2311.90 m (64-bit).

**Comment by alligilmore** [comment]
This is happening to me too, running python 2.7.6 and Safari (OS X 10.10.2). So far it seems to be a problem only after I run a full script.

**Comment by glamp** [comment]
should be fixed in 0.4.1

**Comment by princeatul** [comment]
I am still facing the same issue in Rodeo. Not getting any output on using print command.
