### ISSUE TITLE
slugify is not compatible with python3

### ISSUE THREAD

**Issue by stonebig** [yhat/rodeo#90]
````
packages\slugify.py", line 24, in slugify
    unicode(
NameError: name 'unicode' is not defined
````

**Comment by giserh** [comment]
use unicode-slugify

**Comment by stonebig** [comment]
So, if I reduce slufigy.py code to this:
````
`return re.sub(r'[-\s]+', '-',
            (re.sub(r'[^\w\s-]', '',string).strip().lower()))
````
it' doesn't break on python3.

then, on windows / python3:
- the start seems depressively slow (if even it works) on firefox,
- it starts on chrome, but there is an issue in the path of files I click on:
````
FILE DOES NOT EXIST: D:\Scripts/2to3.bat
````
````

**Comment by ricoll** [comment]
Hi stonebigm

I raise the issue #92   and you recommended me to try this but I'm not sure to understand (I'm not very familliar with Python).

What do you mean by 'use unicode-slugify'

**Comment by stonebig** [comment]
Hi ricoll, 

In your Python installation, you should have a `slugify.py` file somewhere, in a sub-directory `...\Lib\site-packages\slugify.py`. 

If you find it and feel adventurous, you can try modify it like below, that should solve the current error you saw.

You can also just wait next iteration of rodeo package, that will hopefully fix this problem and others.

````
`# -*- coding: utf-8 -*-

"""A generic slugifier utility (currently only for Latin-based scripts)."""

import re
import unicodedata

__version__ = '0.0.1'


def slugify(string):

    """
    Slugify a unicode string.

    Example:

        >>> slugify(u"Héllø Wörld")
        u"hello-world"

    """

    return re.sub(r'[-\s]+', '-',
            (re.sub(r'[^\w\s-]', '',string).strip().lower()))
````

**Comment by glamp** [comment]
@stonebig 729d159110fdfd33af1bded56353e02ac6a4e3e9

let me know if this works for you

**Comment by dyngts** [comment]
Hi @glamp,

I'm already update rodeo 0.3.0 -> 0.3.2, but still throw error. Then, i'm trying manually change rodeo.py with your code in [729d159](https://github.com/yhat/rodeo/commit/729d159110fdfd33af1bded56353e02ac6a4e3e9), but still doesn't work.

**Comment by stonebig** [comment]
so, with last hour `whoops` commit 2eede35b75756b10d5931e4ab58f517def18c644:
- no more slugify package problem (normal),
- very good response time of firefox,
- but then when I browse down to `D:\result_tests\winpython-3.4.3.amd64qt5exp\python-3.4.3.amd64\Lib\site-packages\Cython` and click on the next `Tests` subdirectory:
   - I find myself in front of mere `..` entry (even if the directory is not empty),
   - when I click on this ony  `..` entry, I find myself back at the top level.

Is it normal ?

**Comment by stonebig** [comment]
and If I click on a file on the presented base level, it opens in the editor.
but i continue to have a problem if it's a file in a subdirectory:
````
FILE DOES NOT EXIST: D:\Lib/aifc.py
````
for a file which relative path may rather be `.\Lib\aifc.py`
(and absolute path `D:\result_tests\winpython-3.4.3.amd64qt5exp\python-3.4.3.amd64\Lib\aifc.py`)

**Comment by stonebig** [comment]
closing, as initial error in the title is corrected
